"""initial schema

Revision ID: a715f4a894bb
Revises: 
Create Date: 2026-08-26 22:44:37.652222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a715f4a894bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('doctor_id', sa.String(length=40), nullable=True),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('service_id', sa.String(length=40), nullable=True),
    sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_source', sa.String(length=24), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'CONFIRMED', 'RESCHEDULED', 'CANCELLED', 'NO_SHOW', 'COMPLETED', name='appointmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=128), nullable=True),
    sa.Column('no_show', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_appointment_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_appointment_at'), 'appointments', ['appointment_at'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_store_id'), 'appointments', ['store_id'], unique=False)
    op.create_index(op.f('ix_appointments_updated_at'), 'appointments', ['updated_at'], unique=False)
    op.create_table('attributions',
    sa.Column('attribution_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('transaction_id', sa.String(length=40), nullable=True),
    sa.Column('payment_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.Enum('TOUCH', 'TASK', 'CAMPAIGN', 'ORGANIC', 'OTHER', name='attributionsourcetype', native_enum=False, length=16), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('touch_id', sa.String(length=40), nullable=True),
    sa.Column('experiment_id', sa.String(length=40), nullable=True),
    sa.Column('attribution_model', sa.Enum('LAST_TOUCH', 'FIRST_TOUCH', 'RULE_BASED', 'HOLDOUT', name='attributionmodel', native_enum=False, length=16), nullable=False),
    sa.Column('attributed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('incremental_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('attribution_id')
    )
    op.create_index(op.f('ix_attributions_created_at'), 'attributions', ['created_at'], unique=False)
    op.create_index(op.f('ix_attributions_organization_id'), 'attributions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attributions_patient_id'), 'attributions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_attributions_payment_id'), 'attributions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_attributions_store_id'), 'attributions', ['store_id'], unique=False)
    op.create_index(op.f('ix_attributions_updated_at'), 'attributions', ['updated_at'], unique=False)
    op.create_table('campaign_audiences',
    sa.Column('campaign_audience_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.Column('experiment_id', sa.String(length=40), nullable=True),
    sa.Column('experiment_group', sa.Enum('CONTROL', 'TREATMENT_A', 'TREATMENT_B', 'TREATMENT_C', 'NONE', name='experimentgroup', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('campaign_audience_id')
    )
    op.create_index(op.f('ix_campaign_audiences_campaign_id'), 'campaign_audiences', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_created_at'), 'campaign_audiences', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_organization_id'), 'campaign_audiences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_patient_id'), 'campaign_audiences', ['patient_id'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_store_id'), 'campaign_audiences', ['store_id'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_updated_at'), 'campaign_audiences', ['updated_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('ALWAYS_ON', 'SEASONAL', 'HOLIDAY', 'NEW_SERVICE', 'REACTIVATION', name='campaigntype', native_enum=False, length=24), nullable=False),
    sa.Column('objective', sa.Enum('NEW_CUSTOMER', 'REACTIVATION', 'RETENTION', 'PACKAGE_SALES', name='campaignobjective', native_enum=False, length=24), nullable=False),
    sa.Column('target_segment', sa.JSON(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', name='campaignstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_store_id'), 'campaigns', ['store_id'], unique=False)
    op.create_index(op.f('ix_campaigns_updated_at'), 'campaigns', ['updated_at'], unique=False)
    op.create_table('capacities',
    sa.Column('capacity_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=False),
    sa.Column('doctor_id', sa.String(length=40), nullable=True),
    sa.Column('room_id', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('available_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity_minutes', sa.Integer(), nullable=True),
    sa.Column('booked_minutes', sa.Integer(), nullable=True),
    sa.Column('available_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('capacity_id')
    )
    op.create_index(op.f('ix_capacities_created_at'), 'capacities', ['created_at'], unique=False)
    op.create_index(op.f('ix_capacities_organization_id'), 'capacities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_capacities_store_id'), 'capacities', ['store_id'], unique=False)
    op.create_index(op.f('ix_capacities_updated_at'), 'capacities', ['updated_at'], unique=False)
    op.create_table('care_recommendations',
    sa.Column('care_recommendation_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('visit_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('doctor_id', sa.String(length=40), nullable=False),
    sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommendation_type', sa.Enum('REVISIT', 'TREATMENT', 'REVIEW', 'OTHER', name='recommendationtype', native_enum=False, length=16), nullable=False),
    sa.Column('next_visit_recommended', sa.Boolean(), nullable=False),
    sa.Column('recommended_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appointment_should_be_created', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('care_recommendation_id')
    )
    op.create_index(op.f('ix_care_recommendations_created_at'), 'care_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_care_recommendations_organization_id'), 'care_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_care_recommendations_patient_id'), 'care_recommendations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_recommendations_store_id'), 'care_recommendations', ['store_id'], unique=False)
    op.create_index(op.f('ix_care_recommendations_updated_at'), 'care_recommendations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_care_recommendations_visit_id'), 'care_recommendations', ['visit_id'], unique=False)
    op.create_table('content_reviews',
    sa.Column('content_review_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('touch_id', sa.String(length=40), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=512), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('content_review_id')
    )
    op.create_index(op.f('ix_content_reviews_campaign_id'), 'content_reviews', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_reviews_created_at'), 'content_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_reviews_organization_id'), 'content_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_reviews_store_id'), 'content_reviews', ['store_id'], unique=False)
    op.create_index(op.f('ix_content_reviews_updated_at'), 'content_reviews', ['updated_at'], unique=False)
    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('doctor_status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=16), nullable=False),
    sa.Column('specialty', sa.JSON(), nullable=True),
    sa.Column('service_categories', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('working_schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_organization_id'), 'doctors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_doctors_store_id'), 'doctors', ['store_id'], unique=False)
    op.create_index(op.f('ix_doctors_updated_at'), 'doctors', ['updated_at'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=True),
    sa.Column('actor_type', sa.Enum('PATIENT', 'DOCTOR', 'STAFF', 'AI', 'SYSTEM', name='actortype', native_enum=False, length=16), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=40), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_events_patient_id'), 'events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_events_store_id'), 'events', ['store_id'], unique=False)
    op.create_index(op.f('ix_events_updated_at'), 'events', ['updated_at'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('experiment_assignment_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('experiment_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('group', sa.Enum('CONTROL', 'TREATMENT_A', 'TREATMENT_B', 'TREATMENT_C', 'NONE', name='experimentgroup', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('experiment_assignment_id')
    )
    op.create_index(op.f('ix_experiment_assignments_created_at'), 'experiment_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_experiment_id'), 'experiment_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_organization_id'), 'experiment_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_patient_id'), 'experiment_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_store_id'), 'experiment_assignments', ['store_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_updated_at'), 'experiment_assignments', ['updated_at'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('objective', sa.String(length=256), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('primary_metric', sa.String(length=64), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'CANCELLED', name='experimentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_organization_id'), 'experiments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_experiments_store_id'), 'experiments', ['store_id'], unique=False)
    op.create_index(op.f('ix_experiments_updated_at'), 'experiments', ['updated_at'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('visit_id', sa.String(length=40), nullable=True),
    sa.Column('feedback_type', sa.Enum('REVIEW', 'COMPLAINT', 'SURVEY', name='feedbacktype', native_enum=False, length=16), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('complaint_flag', sa.Boolean(), nullable=False),
    sa.Column('complaint_category', sa.String(length=128), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_organization_id'), 'feedback', ['organization_id'], unique=False)
    op.create_index(op.f('ix_feedback_patient_id'), 'feedback', ['patient_id'], unique=False)
    op.create_index(op.f('ix_feedback_store_id'), 'feedback', ['store_id'], unique=False)
    op.create_index(op.f('ix_feedback_updated_at'), 'feedback', ['updated_at'], unique=False)
    op.create_table('followups',
    sa.Column('followup_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('related_visit_id', sa.String(length=40), nullable=True),
    sa.Column('related_appointment_id', sa.String(length=40), nullable=True),
    sa.Column('staff_id', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Enum('POST_VISIT_CARE', 'REVISIT_REMINDER', 'NO_SHOW', 'TREATMENT_INTERRUPTION', 'SLEEPING_CUSTOMER', 'PACKAGE_EXPIRY', 'CAMPAIGN', 'COMPLAINT', 'OTHER', name='followupreason', native_enum=False, length=32), nullable=False),
    sa.Column('channel', sa.Enum('PHONE', 'SMS', 'WECHAT', 'ENTERPRISE_WECHAT', 'MANUAL', name='followupchannel', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='followupstatus', native_enum=False, length=16), nullable=False),
    sa.Column('result', sa.Enum('NO_ANSWER', 'INVALID_CONTACT', 'REPLIED', 'NOT_INTERESTED', 'INTERESTED', 'APPOINTMENT_CREATED', 'VISITED', 'CONVERTED', 'DO_NOT_CONTACT', name='followupresult', native_enum=False, length=32), nullable=True),
    sa.Column('customer_response', sa.String(length=512), nullable=True),
    sa.Column('next_action', sa.String(length=256), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appointment_created_id', sa.String(length=40), nullable=True),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('followup_id')
    )
    op.create_index(op.f('ix_followups_created_at'), 'followups', ['created_at'], unique=False)
    op.create_index(op.f('ix_followups_organization_id'), 'followups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_followups_patient_id'), 'followups', ['patient_id'], unique=False)
    op.create_index(op.f('ix_followups_staff_id'), 'followups', ['staff_id'], unique=False)
    op.create_index(op.f('ix_followups_store_id'), 'followups', ['store_id'], unique=False)
    op.create_index(op.f('ix_followups_updated_at'), 'followups', ['updated_at'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_records_created_at'), 'idempotency_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_updated_at'), 'idempotency_records', ['updated_at'], unique=False)
    op.create_table('lead_sources',
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('ad_id', sa.String(length=64), nullable=True),
    sa.Column('content_id', sa.String(length=64), nullable=True),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('salesperson_id', sa.String(length=40), nullable=True),
    sa.Column('first_touch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_lead_sources_created_at'), 'lead_sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_sources_organization_id'), 'lead_sources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_patient_id'), 'lead_sources', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_store_id'), 'lead_sources', ['store_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_updated_at'), 'lead_sources', ['updated_at'], unique=False)
    op.create_table('message_templates',
    sa.Column('message_template_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.Enum('RECOVERY', 'RETENTION', 'GROWTH', 'APPOINTMENT', 'FOLLOWUP', 'MANAGER_REVIEW', 'DOCTOR_ACTION', name='tasktype', native_enum=False, length=24), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('message_template_id')
    )
    op.create_index(op.f('ix_message_templates_created_at'), 'message_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_templates_organization_id'), 'message_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_message_templates_store_id'), 'message_templates', ['store_id'], unique=False)
    op.create_index(op.f('ix_message_templates_updated_at'), 'message_templates', ['updated_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('service_id', sa.String(length=40), nullable=True),
    sa.Column('package_id', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_organization_id'), 'order_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_order_items_patient_id'), 'order_items', ['patient_id'], unique=False)
    op.create_index(op.f('ix_order_items_store_id'), 'order_items', ['store_id'], unique=False)
    op.create_index(op.f('ix_order_items_updated_at'), 'order_items', ['updated_at'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('visit_id', sa.String(length=40), nullable=True),
    sa.Column('salesperson_id', sa.String(length=40), nullable=True),
    sa.Column('doctor_id', sa.String(length=40), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'CANCELLED', name='orderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_final_amount'), 'orders', ['final_amount'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_orders_patient_id'), 'orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_updated_at'), 'organizations', ['updated_at'], unique=False)
    op.create_table('package_usages',
    sa.Column('package_usage_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('package_instance_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('visit_id', sa.String(length=40), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_id', sa.String(length=40), nullable=True),
    sa.Column('sessions_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('package_usage_id')
    )
    op.create_index(op.f('ix_package_usages_created_at'), 'package_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_package_usages_organization_id'), 'package_usages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_package_usages_package_instance_id'), 'package_usages', ['package_instance_id'], unique=False)
    op.create_index(op.f('ix_package_usages_patient_id'), 'package_usages', ['patient_id'], unique=False)
    op.create_index(op.f('ix_package_usages_store_id'), 'package_usages', ['store_id'], unique=False)
    op.create_index(op.f('ix_package_usages_updated_at'), 'package_usages', ['updated_at'], unique=False)
    op.create_index(op.f('ix_package_usages_visit_id'), 'package_usages', ['visit_id'], unique=False)
    op.create_table('packages',
    sa.Column('package_instance_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('package_template_id', sa.String(length=40), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('total_sessions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_sessions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_sessions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'REFUNDED', 'PAUSED', name='packagestatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('package_instance_id')
    )
    op.create_index(op.f('ix_packages_created_at'), 'packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_packages_organization_id'), 'packages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_packages_patient_id'), 'packages', ['patient_id'], unique=False)
    op.create_index(op.f('ix_packages_store_id'), 'packages', ['store_id'], unique=False)
    op.create_index(op.f('ix_packages_updated_at'), 'packages', ['updated_at'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('wechat', sa.String(length=128), nullable=True),
    sa.Column('enterprise_wechat_id', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('first_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('primary_doctor_id', sa.String(length=40), nullable=True),
    sa.Column('primary_staff_id', sa.String(length=40), nullable=True),
    sa.Column('customer_status', sa.Enum('ACTIVE', 'SLEEPING', 'LOST', 'NEW', 'BLOCKED', name='customerstatus', native_enum=False, length=16), nullable=False),
    sa.Column('customer_stage', sa.Enum('FIRST_VISIT', 'REVISIT', 'TREATMENT', 'COMPLETED', 'DORMANT', name='customerstage', native_enum=False, length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('referrer_patient_id', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('consent_status', sa.String(length=16), nullable=True),
    sa.Column('dnc', sa.Boolean(), nullable=False),
    sa.Column('complaint_flag', sa.Boolean(), nullable=False),
    sa.Column('contact_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_last_visit_date'), 'patients', ['last_visit_date'], unique=False)
    op.create_index(op.f('ix_patients_mobile'), 'patients', ['mobile'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patients_store_id'), 'patients', ['store_id'], unique=False)
    op.create_index(op.f('ix_patients_updated_at'), 'patients', ['updated_at'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('WECHAT', 'ALIPAY', 'CASH', 'CARD', 'OTHER', name='paymentmethod', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REVERSED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_store_id'), 'payments', ['store_id'], unique=False)
    op.create_index(op.f('ix_payments_updated_at'), 'payments', ['updated_at'], unique=False)
    op.create_table('refunds',
    sa.Column('refund_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('refund_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_organization_id'), 'refunds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refunds_patient_id'), 'refunds', ['patient_id'], unique=False)
    op.create_index(op.f('ix_refunds_store_id'), 'refunds', ['store_id'], unique=False)
    op.create_index(op.f('ix_refunds_updated_at'), 'refunds', ['updated_at'], unique=False)
    op.create_table('review_sessions',
    sa.Column('review_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('actions_kept', sa.JSON(), nullable=True),
    sa.Column('actions_dropped', sa.JSON(), nullable=True),
    sa.Column('next_week_plan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_sessions_created_at'), 'review_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_sessions_organization_id'), 'review_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_store_id'), 'review_sessions', ['store_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_updated_at'), 'review_sessions', ['updated_at'], unique=False)
    op.create_table('services',
    sa.Column('service_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('service_category', sa.String(length=64), nullable=False),
    sa.Column('standard_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommended_cycle_days', sa.Integer(), nullable=True),
    sa.Column('recommended_visit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_organization_id'), 'services', ['organization_id'], unique=False)
    op.create_index(op.f('ix_services_service_category'), 'services', ['service_category'], unique=False)
    op.create_index(op.f('ix_services_store_id'), 'services', ['store_id'], unique=False)
    op.create_index(op.f('ix_services_updated_at'), 'services', ['updated_at'], unique=False)
    op.create_table('staff',
    sa.Column('staff_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ASSISTANT', 'CUSTOMER_SERVICE', 'THERAPIST', 'SALES', 'MANAGER', 'OTHER', name='staffrole', native_enum=False, length=32), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_created_at'), 'staff', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_organization_id'), 'staff', ['organization_id'], unique=False)
    op.create_index(op.f('ix_staff_store_id'), 'staff', ['store_id'], unique=False)
    op.create_index(op.f('ix_staff_updated_at'), 'staff', ['updated_at'], unique=False)
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_name', sa.String(length=128), nullable=False),
    sa.Column('store_type', sa.Enum('TCM_CLINIC', 'OUTPATIENT', 'PHYSIOTHERAPY', 'OTHER', name='storetype', native_enum=False, length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('business_status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='businessstatus', native_enum=False, length=16), nullable=False),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('number_of_doctors', sa.Integer(), nullable=True),
    sa.Column('number_of_staff', sa.Integer(), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('monthly_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_stores_created_at'), 'stores', ['created_at'], unique=False)
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stores_updated_at'), 'stores', ['updated_at'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('task_type', sa.Enum('RECOVERY', 'RETENTION', 'GROWTH', 'APPOINTMENT', 'FOLLOWUP', 'MANAGER_REVIEW', 'DOCTOR_ACTION', name='tasktype', native_enum=False, length=24), nullable=False),
    sa.Column('patient_id', sa.String(length=40), nullable=True),
    sa.Column('assigned_to_type', sa.Enum('STAFF', 'DOCTOR', 'ROLE', 'AI', name='assignedtotype', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Enum('S', 'A', 'B', 'C', name='taskpriority', native_enum=False, length=4), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', name='taskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('related_followup_id', sa.String(length=40), nullable=True),
    sa.Column('suggested_channel', sa.String(length=24), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_template_id', sa.String(length=40), nullable=True),
    sa.Column('related_campaign_id', sa.String(length=40), nullable=True),
    sa.Column('related_experiment_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.Enum('SYSTEM', 'AI', 'STAFF', 'DOCTOR', name='createdbytype', native_enum=False, length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_patient_id'), 'tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_store_id'), 'tasks', ['store_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_table('touches',
    sa.Column('touch_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('followup_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.Enum('PHONE', 'SMS', 'WECHAT', 'ENTERPRISE_WECHAT', 'OFFICIAL_ACCOUNT', 'MANUAL', name='touchchannel', native_enum=False, length=24), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_template_id', sa.String(length=40), nullable=True),
    sa.Column('message_version', sa.String(length=32), nullable=True),
    sa.Column('delivery_status', sa.Enum('SENT', 'DELIVERED', 'FAILED', name='deliverystatus', native_enum=False, length=16), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('touch_id')
    )
    op.create_index(op.f('ix_touches_campaign_id'), 'touches', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_touches_created_at'), 'touches', ['created_at'], unique=False)
    op.create_index(op.f('ix_touches_organization_id'), 'touches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_touches_patient_id'), 'touches', ['patient_id'], unique=False)
    op.create_index(op.f('ix_touches_sent_at'), 'touches', ['sent_at'], unique=False)
    op.create_index(op.f('ix_touches_store_id'), 'touches', ['store_id'], unique=False)
    op.create_index(op.f('ix_touches_updated_at'), 'touches', ['updated_at'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('treatment_plan_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('visit_id', sa.String(length=40), nullable=False),
    sa.Column('doctor_id', sa.String(length=40), nullable=False),
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('recommended_next_visit_date', sa.Date(), nullable=True),
    sa.Column('recommended_next_visit_min_date', sa.Date(), nullable=True),
    sa.Column('recommended_next_visit_max_date', sa.Date(), nullable=True),
    sa.Column('recommended_total_visits', sa.Integer(), nullable=True),
    sa.Column('completed_visits', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='treatmentplanstatus', native_enum=False, length=16), nullable=False),
    sa.Column('next_action', sa.String(length=256), nullable=True),
    sa.Column('next_action_owner', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('treatment_plan_id')
    )
    op.create_index(op.f('ix_treatment_plans_created_at'), 'treatment_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_treatment_plans_organization_id'), 'treatment_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_store_id'), 'treatment_plans', ['store_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_updated_at'), 'treatment_plans', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('visits',
    sa.Column('visit_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('appointment_id', sa.String(length=40), nullable=True),
    sa.Column('doctor_id', sa.String(length=40), nullable=False),
    sa.Column('staff_id', sa.String(length=40), nullable=True),
    sa.Column('visit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_type', sa.Enum('FIRST_VISIT', 'FOLLOWUP', 'TREATMENT', 'REVIEW', 'CONSULTATION', 'OTHER', name='visittype', native_enum=False, length=24), nullable=False),
    sa.Column('service_category', sa.String(length=64), nullable=True),
    sa.Column('first_visit_flag', sa.Boolean(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_status', sa.Enum('CHECKED_IN', 'COMPLETED', 'CANCELLED', name='visitstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_visits_appointment_id'), 'visits', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_visits_created_at'), 'visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_organization_id'), 'visits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visits_store_id'), 'visits', ['store_id'], unique=False)
    op.create_index(op.f('ix_visits_updated_at'), 'visits', ['updated_at'], unique=False)
    op.create_index(op.f('ix_visits_visit_at'), 'visits', ['visit_at'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=40), nullable=False),
    sa.Column('subscription_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_webhook_deliveries_created_at'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_subscription_id'), 'webhook_deliveries', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_updated_at'), 'webhook_deliveries', ['updated_at'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('subscription_id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_created_at'), 'webhook_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_organization_id'), 'webhook_subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_updated_at'), 'webhook_subscriptions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_subscriptions_updated_at'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_organization_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_created_at'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_deliveries_updated_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_subscription_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_created_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_visits_visit_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_updated_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_store_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_organization_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_created_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_appointment_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatment_plans_updated_at'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_store_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_organization_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_created_at'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_touches_updated_at'), table_name='touches')
    op.drop_index(op.f('ix_touches_store_id'), table_name='touches')
    op.drop_index(op.f('ix_touches_sent_at'), table_name='touches')
    op.drop_index(op.f('ix_touches_patient_id'), table_name='touches')
    op.drop_index(op.f('ix_touches_organization_id'), table_name='touches')
    op.drop_index(op.f('ix_touches_created_at'), table_name='touches')
    op.drop_index(op.f('ix_touches_campaign_id'), table_name='touches')
    op.drop_table('touches')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_store_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_patient_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_stores_updated_at'), table_name='stores')
    op.drop_index(op.f('ix_stores_organization_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_created_at'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_staff_updated_at'), table_name='staff')
    op.drop_index(op.f('ix_staff_store_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_organization_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_created_at'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_services_updated_at'), table_name='services')
    op.drop_index(op.f('ix_services_store_id'), table_name='services')
    op.drop_index(op.f('ix_services_service_category'), table_name='services')
    op.drop_index(op.f('ix_services_organization_id'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_review_sessions_updated_at'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_store_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_organization_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_created_at'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index(op.f('ix_refunds_updated_at'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_store_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_patient_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_organization_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payments_updated_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_store_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_patients_updated_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_store_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_mobile'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_visit_date'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_packages_updated_at'), table_name='packages')
    op.drop_index(op.f('ix_packages_store_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_patient_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_organization_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_created_at'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_package_usages_visit_id'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_updated_at'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_store_id'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_patient_id'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_package_instance_id'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_organization_id'), table_name='package_usages')
    op.drop_index(op.f('ix_package_usages_created_at'), table_name='package_usages')
    op.drop_table('package_usages')
    op.drop_index(op.f('ix_organizations_updated_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_patient_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_final_amount'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_items_updated_at'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_store_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_patient_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_organization_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_message_templates_updated_at'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_store_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_organization_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_created_at'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_lead_sources_updated_at'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_store_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_patient_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_organization_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_created_at'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_idempotency_records_updated_at'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_created_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_followups_updated_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_store_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_staff_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_patient_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_organization_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_created_at'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_feedback_updated_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_store_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_patient_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_organization_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_experiments_updated_at'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_store_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_organization_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_experiment_assignments_updated_at'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_store_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_patient_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_organization_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_experiment_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_created_at'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_events_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_store_id'), table_name='events')
    op.drop_index(op.f('ix_events_patient_id'), table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_doctors_updated_at'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_store_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_organization_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_content_reviews_updated_at'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_store_id'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_organization_id'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_created_at'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_campaign_id'), table_name='content_reviews')
    op.drop_table('content_reviews')
    op.drop_index(op.f('ix_care_recommendations_visit_id'), table_name='care_recommendations')
    op.drop_index(op.f('ix_care_recommendations_updated_at'), table_name='care_recommendations')
    op.drop_index(op.f('ix_care_recommendations_store_id'), table_name='care_recommendations')
    op.drop_index(op.f('ix_care_recommendations_patient_id'), table_name='care_recommendations')
    op.drop_index(op.f('ix_care_recommendations_organization_id'), table_name='care_recommendations')
    op.drop_index(op.f('ix_care_recommendations_created_at'), table_name='care_recommendations')
    op.drop_table('care_recommendations')
    op.drop_index(op.f('ix_capacities_updated_at'), table_name='capacities')
    op.drop_index(op.f('ix_capacities_store_id'), table_name='capacities')
    op.drop_index(op.f('ix_capacities_organization_id'), table_name='capacities')
    op.drop_index(op.f('ix_capacities_created_at'), table_name='capacities')
    op.drop_table('capacities')
    op.drop_index(op.f('ix_campaigns_updated_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_store_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_campaign_audiences_updated_at'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_store_id'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_patient_id'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_organization_id'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_created_at'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_campaign_id'), table_name='campaign_audiences')
    op.drop_table('campaign_audiences')
    op.drop_index(op.f('ix_attributions_updated_at'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_store_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_payment_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_patient_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_organization_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_created_at'), table_name='attributions')
    op.drop_table('attributions')
    op.drop_index(op.f('ix_appointments_updated_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_store_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_at'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###